### ISSUE TITLE
doesn't work on pythonanywhere

### ISSUE THREAD

**Issue by jordangpt89** [Thiru-Malai/ChatGPT-WhatsappBot-Twilio#2]
I can't get this to work on pythonanywhere and it completely breaks. Any advice or recommendations?

**Comment by Thiru-Malai** [comment]
What exactly is the issue you are facing?

**Comment by jordangpt89** [comment]
I have it running and I add the webhook to Twilio and I do not get a response in Whatsapp...
<img width="1702" alt="Screenshot 2023-04-10 at 11 59 53" src="https://user-images.githubusercontent.com/5709279/230889631-7774815f-e560-423a-89b8-d70bb2a0c028.png">

I don't know how to fix it.

**Comment by jordangpt89** [comment]
Should I set up my PythonAnywhere webapp as manual configuration or use Flask configuration? 

Twilio is only seeing page not found: 404

<img width="1419" alt="Screenshot 2023-04-10 at 12 19 24" src="https://user-images.githubusercontent.com/5709279/230893755-9951e662-fe26-4ecf-9d37-033c75fa10c3.png">

**Comment by jordangpt89** [comment]
Also I have another question, can I work with you to upgrade this from davinici model syntax to gpt-3.5-turbo model because the syntax is different

**Comment by jordangpt89** [comment]
can we connect so i can hire you to help me?

**Comment by Thiru-Malai** [comment]
Let me have a look and update you. No sir I am currently unavailable so it is not possible now to work with me. But I can definitely work with you in the near future 

But I will get your issue fixed asap

**Comment by Thiru-Malai** [comment]
So you shouldn't be running like the way you do.

![image](https://user-images.githubusercontent.com/73980589/231989530-27e342fa-7791-4ecc-a532-ae2c5a11dd25.png)

I guess you have followed these steps for installation.

Then:
1. Create a web application in pythonanywhere.com
2. Select Manual Configuration
3. Choose Python 3.8
4. In the next window that opens click next.
5. After that you can see a simple Hello World Application.
6. Go back to the PythonAnywhere web application page. Scroll down to the section titled “Virtualenv”. In this section you have to configure the location of the virtual environment created earlier. Click on the “Enter path” line, and then type /home/<your-username>/venv, making sure to use type your PythonAnywhere username instead of <your-username>.
7. Now find the section titled “Code”. The “WSGI configuration file” line has the full path of the WSGI configuration template file added by PythonAnywhere, which should have the format /var/www/<your-username>_pythonanywhere_com_wsgi.py:
8. Done

If you face any issues let me know

Contact me through:
https://www.linkedin.com/in/thirumalaikg/

**Comment by jordangpt89** [comment]
Is there anything I need to change in step 7? I think you forgot to add something to change in the _pythonanywhere_com_wsgi.py ??

If I complete all the steps, I do not get a response still.

**Comment by Thiru-Malai** [comment]
Yes. You need to add this line in the pythonanywhere_com_wsgi.py file.
`from main import app as application`

**Comment by ayush20501** [comment]
I am running free main.py locally but it's showing not found!

**Comment by ayush20501** [comment]
> I can't get this to work on pythonanywhere and it completely breaks. Any advice or recommendations?

are you able to run the app locally?

**Comment by ShubhamJ010** [comment]
can all of this be done using free openAi api ??

**Comment by Thiru-Malai** [comment]
No. Open AI is now paid. So if you have a paid api key of open AI it will work fine

**Comment by noelram** [comment]
I still got 
No module named 'flask'
File "/home/<myuser>/ChatGPT/main.py", line 1, in <module>
from flask import Flask, request, session.

Could you help me?

**Comment by Thiru-Malai** [comment]
Can you please tell me how to reproduce the error?

Try:
pip install Flask in bash console of pythonanywhere

Please make sure you follow this process

![image](https://github.com/Thiru-Malai/ChatGPT-WhatsappBot-Twilio/assets/73980589/c833d97e-78da-4ebf-bfde-94ef2404d588)

**Comment by noelram** [comment]
> Can you please tell me how to reproduce the error?
> 
> Try: pip install Flask in bash console of pythonanywhere
> 
> Please make sure you follow this process
> 
> ![image](https://user-images.githubusercontent.com/73980589/266782377-c833d97e-78da-4ebf-bfde-94ef2404d588.png)

Thanks. I was able to make it work.
